### ISSUE TITLE
Repeat of defaults reported

### ISSUE THREAD

**Issue by ahayes** [abhigenie92/unattended_upgrades_repos#2]
It would appear that the script lists repos that are already included (after interpretation.)

For example, on Ubuntu 16.04, it suggests adding:
```
"Ubuntu:xenial-updates";
"Ubuntu:xenial";
"Ubuntu:xenial-backports";
"Ubuntu:xenial-security";
```
When the 50unattended-upgrades file already includes:
```
"${distro_id}:${distro_codename}";
"${distro_id}:${distro_codename}-security";
"${distro_id}:${distro_codename}-updates";
"${distro_id}:${distro_codename}-backports";
```

**Comment by abhigenie92** [comment]
Hi Amos,
Thanks for pointing out the issue! The detailed information you provided was really helpful as well!
It should be fixed now, please do `git pull` and check. :)
